<?php 

/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2014
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_page']['pct_megamenu'][0]	= 'MegeMenü aktivieren';
$GLOBALS['TL_LANG']['tl_page']['pct_megamenu'][1]	= 'Aktivieren Sie die MegaMenü-Funktion.';
$GLOBALS['TL_LANG']['tl_page']['pct_mm_article'][0]	= 'Artikel einfügen';
$GLOBALS['TL_LANG']['tl_page']['pct_mm_article'][1]	= 'Wählen Sie den Include-Artikel.';
$GLOBALS['TL_LANG']['tl_page']['pct_mm_replace'][0]	= 'Link ersetzen';
$GLOBALS['TL_LANG']['tl_page']['pct_mm_replace'][1]	= 'Ist diese Option aktiv, wird der gesamte link ersetzt.';
